name: Publish release
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Build
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name="DimUnits-$tag"
          
          # Build archive
          dotnet publish src/DimUnits/DimUnits -c Release -o "$release_name" /p:AssemblyVersion="$tag"
          tar czvf "${release_name}.tar.gz" "$release_name"
          rm -r "$release_name"
          
          # Build nuget package
          dotnet pack -c Release -o "$release_name" /p:AssemblyVersion="$tag"
          
      - name: Publish archive
        uses: softprops/action-gh-release@v1
        with:
          files: "DimUnits*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1
      
      - name: Publish NuGet package
        run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}